### ISSUE TITLE
Move the "status" badge 

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer-ui#108]
In the process detail page, we want to split the "parameters" labels (static ones) from the "status" badge (dynamic) to improve the readability and hierarchy of the information by moving the status badge up & align it with the "Process Details" title.

![image](https://user-images.githubusercontent.com/6894329/229494152-eed256cb-4b7b-48c8-afd9-6657c87c9927.png)

**Comment by selankon** [comment]
> Looks like a good moment to try and use `@vocdoni/react-component`'s `<ElectionStatusBadge />` component eyes

True let me check

**Comment by selankon** [comment]
I cannot do it yet because processes list page isn't migrated yet to use the SDK. I opened a new issue

https://github.com/vocdoni/explorer-ui/issues/111

**Comment by selankon** [comment]
#110 closes this
