### ISSUE TITLE
Refactor components folder 

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer-ui#116]
On [this review](https://github.com/vocdoni/explorer-ui/pull/114#discussion_r1171370569) with @elboletaire we where talking to change the components convention to be more feature based, something like: 

```
components
├── Election
    └── Stats
        └── HeroBanner.tsx
├── Organization
    └── Profile.tsx
```

Using PascalCase. We have to decide a little bit more and do the refactor not all at once.

**Comment by elboletaire** [comment]
My proposition is, as I was saying in the review, to always avoid creating more than two levels inside the `components` folder, and to use business logic domains as folder names. Also, since the components names convention is to name them in PascalCase, any file containing components should be named that way (unless it's an `index.tsx` file, ofc).

Using `index.tsx` files is only recommended when a component has multiple parts, so we would create a folder for it, named following the component's name.

Here's an extended representation of what I'm saying:

    src or root (depending on the project [nextjs != CRA])
    ├── components
    │   ├── Layout
    │   │   └── Banner
    │   │       ├── Badge.tsx (contains the Badge component structure)
    │   │       └── HeroBanner.tsx (contains the HeroBanner component structure)
    │   ├── Election
    │   │   ├── Stats
    │   │   │   ├── HeroBanner.tsx (uses the HeroBanner layout component to represent election stats data)
    │   │   │   └── Badges.tsx (uses the Badge layout component to show multiple election stats as badges)
    │   │   └── View.tsx
    │   ├── Organization
    │   │   ├── Stats
    │   │   │   ├── HeroBanner.tsx (uses the HeroBanner layout component to represent election stats data)
    │   │   │   └── Badges.tsx (uses the Badge layout component to show multiple election stats as badges)
    │   │   └── Profile.tsx
    ├── theme
    │   ├── components (theme styles directly linked to components)
    │   │   ├── BadgeTheme
    │   │   └── BannerTheme
    │   ├── colors.tsx
    │   └── index.tsx (exports the theme object)
    └── constants.tsx

**Comment by selankon** [comment]
After talk on weekly meeting, we talked to do this refactoring when more parts of the explorer are migrated to ui components and the sdk in order to also clean old and unused code inherited from Vocdoni App

**Comment by elboletaire** [comment]
Well that's what I meant to do the upgrade "as other things were updated". Making a full refactor of all this is kinda insane, but anyway the "protocol" or the basis to be followed should still be defined; otherwise you won't know what to update.

**Comment by selankon** [comment]
This is one step on the way to fix this. 

https://github.com/vocdoni/explorer-ui/pull/148

It has 43 files changed, so in order to help reviewers I am going to do little PR's until this is fixed.
