### ISSUE TITLE
Migrate to @vocdoni/chakra-components

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer-ui#124]
Use the new [@vocdoni/chakra-components](https://www.npmjs.com/package/@vocdoni/chakra-components). Use also the new organization provider and the organization components.

**Comment by selankon** [comment]
Actually if we use chakra-components an error is rised: 

```
Navigator is undefined
```

Probably this is an error of how the ckakra components handle the internationalization, calling the Navigator object to check navigator language. This causes an error when Next do the SSR, because navigator is unavailable

**Comment by elboletaire** [comment]
fyi this is known and needs to be fixed https://github.com/vocdoni/ui-components/issues/26

**Comment by selankon** [comment]
After closing this https://github.com/vocdoni/explorer-ui/pull/151 I ave to recheck if there is any other component I can reuse before closing the issue

**Comment by elboletaire** [comment]
Super-seeded by the new explorer https://github.com/vocdoni/explorer
