### ISSUE TITLE
bug: selected language does not get stored

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/explorer-ui#152]
**Describe the bug**
If you change the language of the explorer to a different one than the one it loaded it (it detects your browser language, which is good), it does not get stored, and simply refreshing the page will switch back to the other language.

**To Reproduce**
- Open the explorer
- Change the language to a different one than the currently selected
- Refresh

**Current behavior**
The language switches back to the one detected in your browser.

**Expected behavior**
To stay in the selected language (the language detection feature still needs to be there, for the very first time the user accesses).

**Comment by selankon** [comment]
see https://github.com/vocdoni/ui-scaffold/commit/3dab99f5ae3fd3a8c0b4a5cc2ae71097f2f8729a

**Comment by selankon** [comment]
This solution causes Hydration problem. 

Probably, the server side rendering is, for example in English but the client side in any other language. Lets see how to fix it

**Comment by selankon** [comment]
This is happening when a value is set on the local storage and is accessed and used to render before all the page is load.  

To fix this problems the [usual way](https://stackoverflow.com/a/73411103/4708664) is to add the local storage access inside a `useEffect`, which actually is what we do to detect the browser language:

https://github.com/vocdoni/explorer-ui/blob/4fc18554e27d9841bc31d65ab93d92e3225364ed/components/blocks/language-selector.tsx#L20-L26

A solution can be find how to start the `LanguageDetector` inside a `useEffect` or do it manually doing something like:

```ts
// When setting the language
            if (window && 'localStorage' in window) {
              window.localStorage.setItem('vocdoni.lang', k)
            }
// And inside the useEffect adding browser language detection
const storedLang = () => {
  if (window && 'localStorage' in window) {
    return window.localStorage.getItem('vocdoni.lang') || fallbackLng
  }
  return fallbackLng
}
```

**Comment by selankon** [comment]
Finally I used the functions that implement the `LanguageDetector` package to reuse their logic
