### ISSUE TITLE
bug: "Vote recount" is misleading, should be "Envelope recount"

### ISSUE THREAD

**Issue by altergui** [vocdoni/explorer-ui#166]
![image](https://github.com/vocdoni/explorer-ui/assets/2815267/64747667-f08c-422f-ae23-f36797f5425e)
here you can see "Vote recount 1" and then an option with 20000 votes, which sounds fraudulent.

i believe it should be "Envelope recount", also in line with the button "Show envelopes"

this would involve updating the spanish and catalan as well, but in that case it's a wider issue since many other instances of "envelopes" are translated to "votes" ("sobres" SGTM in see_raw_envelopment_content)
https://github.com/vocdoni/explorer-ui/blob/2c1d178db0dc67bf677b234a663a430c78056a82/i18n/locales/es.json#L235-L240

**Comment by selankon** [comment]
I am not sure to use "recuento de sobres" on CA or ES... Btw, I'll change this for EN
