### ISSUE TITLE
Bump vocdoni packages

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer-ui#168]
In order to start to implement #124 the vocdoni packages are needed to be upgraded. 

![image](https://github.com/vocdoni/explorer-ui/assets/16777076/81a2846f-aa67-4edb-a883-57f5af47bc00)

However, after trying to upgrade them, Next don't start with an error on webpack. Some tries to fix this are located on [f/bump-vocdoni-packages](https://github.com/vocdoni/explorer-ui/tree/f/bump-vocdoni-packages).

![image](https://github.com/vocdoni/explorer-ui/assets/16777076/c0b4af0c-2ed6-4fd1-be86-f895bc04d89e)

**Comment by elboletaire** [comment]
Just to add more context: webpack is loading web-worker's node version, instead of the browser one. The fix is probably forcing webpack to load that browser version instead, but it's webpack... and it's embedded on next.js (via next.config.js). It ain't gonna be easy.

**Comment by selankon** [comment]
Another possible solutions, ftr, are to try to use turbo https://nextjs.org/docs/architecture/turbopack (which is not working atm)

**Comment by selankon** [comment]
After little bit more of research, new lines are opened. 

I tried to use this webpack configuration (but didn't work):

```js
    if (!isServer) {
      config.resolve.alias['web-worker'] = require.resolve('web-worker/import/browser');
      // config.resolve.alias['web-worker'] = require.resolve('web-worker/cjs/browser.js');
    }
 ```

Then, discarded the option to migrate next to turbopack because don't support next build https://nextjs.org/docs/architecture/turbopack#unsupported-features

Another option is to remove next featrues from the explorer to use vite instead. Atm next is not really used on the whole app:

```bash
➜ grep -rn "'next/" --exclude-dir=node_modules
components/redirect.tsx:1:import { useRouter } from 'next/router';
components/blocks/list-items.tsx:2:import Link from 'next/link';
components/elements/checkbox.tsx:2:import Link from 'next/link';
components/elements/button.tsx:2:import Link from 'next/link';
components/elements/cards.tsx:2:import Link from 'next/link';
components/elements/card-generic.tsx:5:import Link from 'next/link';
components/pages/app/header.tsx:3:import Link from 'next/link';
components/pages/app/components/get-links.tsx:9:import Link from 'next/link';
components/pages/app/layout/verify.tsx:9:// import { useRouter } from 'next/router'
components/pages/app/layout/layout.tsx:2:import { useRouter } from 'next/router';
components/pages/app/footer.tsx:3:import Link from 'next/link';
components/pages/stats/index.tsx:16:import Link from 'next/link';
components/pages/blocks/details/index.tsx:7:import Link from 'next/link';
grep: .next/cache/webpack/server-development/0.pack: binary file matches
grep: .next/cache/webpack/client-development-fallback/0.pack: binary file matches
grep: .next/cache/webpack/client-development/0.pack: binary file matches
hooks/use-pagination-router.tsx:1:import { useRouter } from 'next/router';
hooks/use-pagination-router.tsx:2:import Router from 'next/router';
pages/verify/index.tsx:7:import Router from 'next/router';
pages/_error.tsx:1:import NextError from 'next/error';
pages/_app.tsx:4:import { AppInitialProps } from 'next/app';
pages/_app.tsx:6:import Head from 'next/head';
pages/_app.tsx:7:import { Router } from 'next/router';
pages/_document.tsx:1:import Document from 'next/document';
pages/index/featured.tsx:10:import Link from 'next/link';
```

So could be a solution

**Comment by selankon** [comment]
After reading [docs](https://webpack.js.org/configuration/resolve/), I tried: 

```js
    config.resolve.fallback = {
       //...
      'web-worker': require.resolve('web-worker/browser'),
    };
```

The problem with any try to force to load browser instead of node is all the time the same.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './browser' is not defined by "exports"
```

**Comment by selankon** [comment]
Finally worked using older version of a web worker

```
  "resolutions": {
    "web-worker": "1.2.0"
  },
````

**Comment by selankon** [comment]
Now the problem is a SSR problem due the web workers:

```
Error occurred prerendering page "/processes/show". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at createWebWorker (file:///home/vocdoni/actions-runner-1/_work/explorer-ui/explorer-ui/node_modules/@vocdoni/react-providers/dist/chunk-TOEVJIKX.js:5:21)
```

**Comment by elboletaire** [comment]
> Now the problem is a SSR problem due the web workers:
> 
> ```
> Error occurred prerendering page "/processes/show". Read more: https://nextjs.org/docs/messages/prerender-error
> ReferenceError: window is not defined
>     at createWebWorker (file:///home/vocdoni/actions-runner-1/_work/explorer-ui/explorer-ui/node_modules/@vocdoni/react-providers/dist/chunk-TOEVJIKX.js:5:21)
> ```

It's probably related to the way we load the current url for the webworker in ui-components, see:

https://github.com/vocdoni/ui-components/blob/main/packages/react-providers/src/worker/webWorker.ts#L4

Maybe adding a `|| import.meta.url` would be enough (?)

**Comment by selankon** [comment]
FTR I tried to dynamically import the component and the build passed but when running `yarn dev` it fails with a random error that i am not sure if its completely related. I will try to fix as suggested by @elboletaire 

To dynamically import: 

```ts
const ProcessHomeNoSSR = dynamic(() => import('@components/pages/elections/details/caca'), {
  ssr: false,
});
```

**Comment by elboletaire** [comment]
Super-seeded by the new explorer https://github.com/vocdoni/explorer
