### ISSUE TITLE
bug: I18n language reverts to default on refresh

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/explorer-ui#170]
**Describe the bug**
Every time I refresh the explorer with English/US as my default language, for about a half of a second the entire page renders in Spanish (catalan?). Then it re-renders in English.

**To Reproduce (please complete the following information)**
Refresh the page with user language set to anything other than the default

**System (please complete the following information):**
Firefox browser on MacOS
Browser default language set to English, location in US

**Comment by elboletaire** [comment]
Super-seeded by the new explorer https://github.com/vocdoni/explorer
