### ISSUE TITLE
Feature Request: Link Envelopes to the transaccion page

### ISSUE THREAD

**Issue by emmdim** [vocdoni/explorer-ui#42]
Also minor modifications in the transaction page should be done to add the envelope field and the corresponding link.
Example: 
 https://explorer.vote/transaction/2639591/0

**Comment by selankon** [comment]
This example is actually not working. Backend send wrong `nullifier` value. 

Realted to https://github.com/vocdoni/vocdoni-node/issues/538#issuecomment-1116448552

**Comment by selankon** [comment]
This is working now
