### ISSUE TITLE
Feature Request: Block <-> Time translator

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/explorer-ui#8]
Requested from @rbaig: an interactive tool where users can calculate estimations between block height and dateTime. Examples of code that does this can be found here: 
https://github.com/vocdoni/vaas-api/blob/b026b4f10aaba21104de8c31f3f41b72c4674b46/urlapi/util.go#L149
and 
https://github.com/vocdoni/vaas-api/blob/b026b4f10aaba21104de8c31f3f41b72c4674b46/urlapi/util.go#L182

I'm happy to help explain how this code would work!

**Comment by selankon** [comment]
Is `VotingApi.estimateDateAtBlock` related?

**Comment by NateWilliams2** [comment]
yes, this function does the same!

**Comment by NateWilliams2** [comment]
yes exactly

**Comment by selankon** [comment]
Hi @NateWilliams2 I merged a simple converter to test it. Need some formatting yet

Check https://github.com/vocdoni/explorer-ui/pull/21 .

I suppose that the block-time converter will vary depending on environment, so I added information about environment and block height. Could be useful to show blockchain stats under the converter? 

See converter: https://dev.explorer.vote/converter
See stats page: https://dev.explorer.vote/stats/

**Comment by NateWilliams2** [comment]
Seems to work great! 
Two comments- 
- I think you're right to include at least some of the stats. The current block height, for example, would be useful on this page
- The interface is not very intuitive to me. I found the four different boxes to be confusing. 
@rbaig thoughts?

**Comment by selankon** [comment]
Hi @NateWilliams2 , 

- As stats, without loading unnecessary info, it show blockheight and `process.env.VOCDONI_ENVIRONMENT` variable. 
- I implemented a more intuitive IU. Now when one input change, the other do also, so there are only two boxes. 

I don't really like the style of the page, probably i will change something later.

Check if is good enough :) Any styling suggestions will be appreciated!

**Comment by rbaig** [comment]
Sorry for the late reply. Thanks for the work.I like the current UI.

Suggestions for improvement:

- What to do when block is set to "0" (which is the default value of the cell)

- How to prevent selecting a date earlier than the genesis block

For future:

-  How to integrate the conversion in other pages. For instance in the process details. I, as a regular user, would appreciate to get this info from the explorer straight

**Comment by selankon** [comment]
Hi,

> What to do when block is set to "0" (which is the default value of the cell)

Yo mean that maybe we should prevent `0` as block height input?

> How to prevent selecting a date earlier than the genesis block

https://github.com/vocdoni/explorer-ui/commit/a5dfc427e41f51704f68c67f49ddfdd29d055542

> How to integrate the conversion in other pages. For instance in the process details. I, as a regular user, would appreciate to get this info from the explorer straight

Easily we could integrate a widget converter on the page. But actually, the process details page has a time block conversion ([ex](https://azeno.explorer.vote/elections/show/#/21b2ea5345d2e0c941dd44ff4c43fc4683088b846ddb3234d1690b0000000000)):

```
Ended 12 days ago

Created on: 12 days ago
```

Is this what you need?
