### ISSUE TITLE
bug: smartphones view is more than 100%

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer-ui#84]
Strange behavior on smartphones makes the view to grow more than 100% width. 

This provokes that menu bar grow more and the menu icon is hidden (you have to horizontally scroll to see it).

I tried different workarrounds to try to find the error without success. 

- Modified this meta tag on `_app.tsx`:

```html
          <meta name="viewport" content="width=device-width, initial-scale=1" />
```

- Tried to disable components on `layout.tsx` to see if was a particular one that causes the error (example, `Footer` or `Header`...)
- Disabled `ChakraProvider` (is this enough? Try uninstalling it)

Everything brings me to think this happened after upgrade to NextJS 13. Need more testing.

**Comment by selankon** [comment]
I can confirm that with the old explorer version on https://explorer.vote/ happen anyway so its not a problem after the frameworks upgrade

**Comment by elboletaire** [comment]
The problem comes from these card-like components:

![imatge](https://user-images.githubusercontent.com/153305/225300125-50f1a3a1-d03b-4a9f-b40d-2099e15ee018.png)
![imatge](https://user-images.githubusercontent.com/153305/225300187-840c8262-6177-46ac-af4a-44bdbccf083d.png)
