### ISSUE TITLE
Feature Request: signify if a process was manually closed

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/explorer-ui#9]
Add a descriptor that details if a process was closed manually, with a setProcessStatus tx, or automatically, by reaching its end block. Additionally include both the original endBlock and the endBlock at which the process was manually ended.

Note- I haven't looked into this in detail, it may not be possible without more features in the scrutinizer API.

**Comment by selankon** [comment]
@marcvelmer  you know if the current API will support this feature?

**Comment by selankon** [comment]
Mmm if this feature have to be implemented should be done SDK side, imho

**Comment by elboletaire** [comment]
Super-seeded by the new explorer https://github.com/vocdoni/explorer

Consider opening a new issue there if you feel this still needs to be implemented there.
