### ISSUE TITLE
Change link and text colors

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer-ui#95]
Right now the links and text color are too bright (difficult to read). Change it to: `rgb(35, 114, 116)`

From:
![image](https://user-images.githubusercontent.com/6894329/227565991-f4771dbf-2ac4-4a18-977b-803b14e311cb.png)

To:
![image](https://user-images.githubusercontent.com/6894329/227566103-b49c624e-9620-4845-bd1a-eb46a41cb3a9.png)

**Comment by selankon** [comment]
Fixed on https://github.com/vocdoni/explorer-ui/commit/de240293b3f3cc27a7e31c8a29bcfd827d532c26
