### ISSUE TITLE
Improve org icon

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer-ui#97]
In the org/process view, all the icons are the Vocdoni logo, but this should only be a placeholder if no other images exist. Use the default org image and if it doesn't work, change it to the default one

![image](https://user-images.githubusercontent.com/6894329/227568014-5600a0d3-e9de-4125-979e-fcd713b00c76.png)

**Comment by selankon** [comment]
The default image is actually the vocdoni logo, but, I guess this organizations doesn't have avatar. Is for that that the logo is all the time the same. 

Have you some example where the avatar logo is effectively another one in order to test it? I cannot find any.

**Comment by jpaulet** [comment]
https://vocdoni.app/entity/#/0x54b7b6b34ed16abdda075817d9dc2cf31488f924 << this entity has an org logo inside vocdoni.app but appears as the default icon in the explorer

**Comment by selankon** [comment]
I see, FTR, this one on azeno:

https://explorer.vote/organizations/show/#/0x54b7b6b34ed16abdda075817d9dc2cf31488f924

```jq
curl https://gw5-azeno.vocdoni.net/dvote -X POST -H Content-Type:application/json --data '{"id": "req00'$RANDOM'", "request": {"method": "getEntityList", "from": 0, "listSize": 10, "searchTerm": "54b7b6b34ed16abdda075817d9dc2cf31488f924", "timestamp":'$(date +%s)'}}' -s | jq 
```

And I created one another one for testing `0xb91CD4fBA665b425EfCF1375f57E54031870632b`:

**Comment by selankon** [comment]
@jpaulet this should be a hotfix for azeno release?
