### ISSUE TITLE
Improve "org" card in the process view

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer-ui#98]
Make the whole organization card clickable (with the cursor) in the process view page:

![image](https://user-images.githubusercontent.com/6894329/227568988-299a40dd-ff15-4e08-81d6-ba3b76d85064.png)

**Comment by selankon** [comment]
https://github.com/vocdoni/explorer-ui/commit/17e3b93a0244ed62faf1448cd36674b528cf5950
