### ISSUE TITLE
Improve "Active" filter on processes pages

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer-ui#99]
The active filter shows ended processes. Solve it to only show active processes (and upcoming ones if there's no difference). 

Ideally, we would show "Upcoming / Active / Paused / Ended / Cancel".

**Comment by selankon** [comment]
This is related to https://github.com/vocdoni/interoperability/issues/8

**Comment by selankon** [comment]
I guess `Upcoming` is not a valid Vochain process state. Valid states, the ones the filter should accept, are: 

```proto
enum ProcessStatus {
	PROCESS_UNKNOWN = 0;
	READY = 1;
	ENDED = 2;
	CANCELED = 3;
	PAUSED = 4;
	RESULTS = 5;
}
```
